### ISSUE TITLE
Create and publish virtual machine

### ISSUE THREAD

**Issue by acka47** [hbz/elag2019-bootcamp#3]
In addition to the SWIB18 VM, also published at http://labs.lobid.org/download/. Add links to readme afterwards.

**Comment by acka47** [comment]
We must also update the docker files.

**Comment by acka47** [comment]
As discussed offline, here are the last adjustments to be made to the virtualbox for the bootcamp.

- [x] delete files to be generated by participants which should be the following in `$ ~/git/elag2019-bootcamp/data`: `loc.json`, `loc-framed.json`~~, `index.html`,~~ 
- [x] ES, Kibana & OpenRefine should be automatically running when starting the VirtualMachine
- [x] Add chromium and gedit shortcut to the desktop
- [x] Add the [JSON formatter browser extension](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa) to chromium
- [x] ~~process.sh must be updated ->~~ pull changes to virtual machine afterwards
- [x] EDIT: add command for starting ES, Kibana and OpenRefine to readme.txt in VM

**Comment by dr0i** [comment]
As the RAM of the VM is only 2GB: restricted the memory consumption of:
- elasticsearch: from 1G to 512M
- openrefine: from 1.4G to 512M-1G

**Comment by dr0i** [comment]
VM image "2019-elag-vm.zip" created, README updated and mail sent.
Closing.
